namespace GoogleSheet.Core.IO.Generator
{
    public class EnumGenerator : ICodeGenerator
    {
        System.Action<string> onGenerateCallback;
        private string enumName;
        private string @namespace = null;
        private string Def = @"
/* Generated By Unity Google Sheet Enum Generator*/
/* author : shlifedev@gmail.com */

using System;
using GoogleSheet.Type;
//@namespace
namespace @header_namespace
{
[Type(type : typeof(@enumName), speractors : new string[] { ""@enumName"" })]
 public class @enumNameEnumType : IType{
 
        public object DefaultValue => default;


        public object Read(string value)
        {
            return (@enumName)Enum.Parse(typeof(@enumName), value); 
        }


        public string Write(object value)
        {
            return value.ToString();
        }
    }
}
";
        public EnumGenerator(string @namespace, string enumName, System.Action<string> onGenerateCallback = null)
        {
            this.@namespace = @namespace;
            this.enumName = enumName;
            this.onGenerateCallback = onGenerateCallback;
        }
        public string Generate()
        {

            var result = Def;
            if (!string.IsNullOrWhiteSpace(@namespace))
            {
                result = result.Replace("@header_namespace", @namespace);
                result = result.Replace("@namespace", "\n using " + this.@namespace + ";\n");
            }
            else
            {
                result = result.Replace("@header_namespace", "GoogleSheet.Type");
            }
            result = result.Replace("@enumName", enumName);
            onGenerateCallback?.Invoke(result);

            return result;
        }
    }
}


