
/* Generated By Unity Google Sheet Enum Generator*/
/* author : shlifedev@gmail.com */

using System;
using Hamster.ZG.Type;
//@namespace
namespace Hamster.ZG.Type
{
[Type(type : typeof(Test2), speractors : new string[] { "Test2" })]
 public class Test2EnumType : IType{
 
        public object DefaultValue => default;


        public object Read(string value)
        {
            return (Test2)Enum.Parse(typeof(Test2), value); 
        }


        public string Write(object value)
        {
            return value.ToString();
        }
    }
}
