
/* Generated By Unity Google Sheet Enum Generator*/
/* author : shlifedev@gmail.com */

using System;
//
 using A.B.C;
namespace Hamster.ZG.Type
{
[Type(type : typeof(Test), speractors : new string[] { "Test" })]
 public class TestType : IType{
 
        public object DefaultValue => default;


        public object Read(string value)
        {
            return (Test)Enum.Parse(typeof(Test), value); 
        }


        public string Write(object value)
        {
            return value.ToString();
        }
    }
}
